ASP.NETSchool/Controllers/GradesController.cs
using ASP.NETSchool.Services;
using ASP.NETSchool.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP.NETSchool.Controllers
{
    [Authorize(Roles ="Teacher, Admin")]
    public class GradesController : Controller
    {
        private GradeService service;

        public GradesController(GradeService gradeService)
        {
            this.service = gradeService;
        }
        public async Task<IActionResult> IndexAsync()
        {
            var allGrades = await service.GetAllGradesAsync();
            return View(allGrades);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var gradesDropdownsData = await service.GetDropdownValuesAsync();
            // v parametrech je skupina dat, value selectu je Id, zobrazuje se LastName
            ViewBag.Students = new SelectList(gradesDropdownsData.Students, "Id", "LastName");
            ViewBag.Subjects = new SelectList(gradesDropdownsData.Subjects, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(GradeViewModel gradeViewModel) // vraci se presmerovani, proto zase IActionResult
        {
            await service.CreateAsync(gradeViewModel);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> EditAsync(int id)
        {
            var gradesDropdownsData = await service.GetDropdownValuesAsync();
            ViewBag.Students = new SelectList(gradesDropdownsData.Students, "Id", "LastName");
            ViewBag.Subjects = new SelectList(gradesDropdownsData.Subjects, "Id", "Name");
            var gradeToEdit = service.GetById(id);
            if (gradeToEdit == null) 
            {
                return View("NotFound");
            }
            return View(gradeToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, GradeViewModel updatedGrade)
        {
            await service.UpdateAsync(updatedGrade);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteAsync(int id)
        {
            await service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

ASP.NETSchool/Controllers/StudentsController.cs
using ASP.NETSchool.Models;
using ASP.NETSchool.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NETSchool.Controllers
{
    [Authorize(Roles = "Teacher, Admin")]
    public class StudentsController : Controller
    {
        public StudentService service;

        public StudentsController(StudentService studentService)
        {
            this.service = studentService;
        }

        public async Task<IActionResult> IndexAsync()   // async za indexem .net core ignoruje
        {
            var allStudents = await service.GetAllAsync();
            return View(allStudents);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(Student student)
        {
            await service.CreateStudentAsync(student);
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Edit(int id)
        {
            var studentToEdit = await service.GetById(id);
            if (studentToEdit == null)
            {
                return View("NotFound");
            }
            return View(studentToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, [Bind("Id, FirstName, LastName, DateOfBirth")] Student student)
        {
            await service.UpdateAsync(student);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var studentToDelete = await service.GetById(id);
            if (studentToDelete == null)
            {
                return View("NotFound");
            }
            await service.DeleteAsync(studentToDelete);
            return RedirectToAction("Index");
        }
    }
}

ASP.NETSchool/Controllers/SubjectsController.cs
using ASP.NETSchool.Models;
using ASP.NETSchool.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NETSchool.Controllers
{
    public class SubjectsController : Controller
    {
        public SubjectService service;

        public SubjectsController(SubjectService subjectService)
        {
            this.service = subjectService;
        }
        public async Task<IActionResult> IndexAsync()   // async za indexem .net core ignoruje
        {
            var allSubjects = await service.GetAllAsync();
            return View(allSubjects);
        }
        [Authorize(Roles = "Admin, Teacher")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(Subject subject)
        {
            await service.CreateSubjectAsync(subject);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, Teacher")]
        public async Task<IActionResult> Edit(int id)
        {
            var subjectToEdit = await service.GetById(id);
            if (subjectToEdit == null)
            {
                return View("NotFound");
            }
            return View(subjectToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, [Bind("Id, Name")] Subject subject)
        {
            await service.UpdateAsync(subject);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, Teacher")]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var subjectToDelete = await service.GetById(id);
            if (subjectToDelete == null)
            {
                return View("NotFound");
            }
            await service.DeleteAsync(subjectToDelete);
            return RedirectToAction("Index");
        }
    }
}

ASP.NETSchool/Controllers/UsersController.cs
using ASP.NETSchool.Models;
using ASP.NETSchool.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NETSchool.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private UserManager<AppUser> _userManager;
        private IPasswordHasher<AppUser> _passwordHasher;
        private IPasswordValidator<AppUser> _passwordValidator;

        public UsersController(UserManager<AppUser> userManager, IPasswordHasher<AppUser> passwordHasher, IPasswordValidator<AppUser> passwordValidator)
        {
            _userManager = userManager;
            _passwordHasher = passwordHasher;
            _passwordValidator = passwordValidator;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                AppUser newUser = new AppUser
                {
                    UserName = userViewModel.Name,
                    Email = userViewModel.Email,
                };
                var result = await _userManager.CreateAsync(newUser, userViewModel.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(userViewModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            AppUser userToEdit = await _userManager.FindByIdAsync(id);
            if (userToEdit == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(userToEdit);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, string email, string password)
        {
            AppUser userToEdit = await _userManager.FindByIdAsync(id);
            if (userToEdit == null)
            {
                ModelState.AddModelError("", "User not found"); // nebo return View("NotFound")
                return View();
            }
            else
            {
                IdentityResult validPassword = null;
                if (!string.IsNullOrEmpty(email))
                {
                    userToEdit.Email = email;
                }
                else
                {
                    ModelState.AddModelError("", "E-mail must not be empty");
                }
                if (!string.IsNullOrEmpty(password))
                {
                    validPassword = await _passwordValidator.ValidateAsync(_userManager, userToEdit, password);
                    if (validPassword.Succeeded == true)
                    {
                        userToEdit.PasswordHash = _passwordHasher.HashPassword(userToEdit, password);
                    }
                    else
                    {
                        foreach (var error in validPassword.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Empty password");
                }
                if (validPassword != null && validPassword.Succeeded)
                {
                    var saveResult = await _userManager.UpdateAsync(userToEdit);
                    if (saveResult.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in saveResult.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
            }
            return View(userToEdit);
        }

        public async Task<IActionResult> Delete(string id)
        {
            AppUser userToDelete = await _userManager.FindByIdAsync(id);
            if (userToDelete == null)
            {
                ModelState.AddModelError("", "User not found");
            }
            else
            {
                var deleteResult = await _userManager.DeleteAsync(userToDelete);
                if (!deleteResult.Succeeded)
                {
                    ModelState.AddModelError("", "Delete unsuccessfull");
                }
            }
            return RedirectToAction("Index");
        }
    }
}

ASP.NETSchool/Views/Shared/AccessDenied.cshtml
<h1 class="text-danger">ACCESS DENIED!</h1>
<a class="btn btn-info" asp-controller="Account" asp-action="Logout">Log out</a>

ASP.NETSchool/Views/Shared/NotFound.cshtml
<h1 class="text-danger">Not Found</h1>

ASP.NETSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NETSchool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NETSchool.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NETSchool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Subjects</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("Teacher") || (User.IsInRole("Admin"))))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Grades" asp-action="Index">Grades</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }
                    </ul>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-success" asp-controller="Account" asp-action="Login" asp-route-returnUrl="/">Log in</a>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-info" asp-controller="Account" asp-action="Logout">Log out</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASP.NETSchool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>