ASP.NETSchool/Models/Student.cs
using System.ComponentModel;

namespace ASP.NETSchool.Models
{
    public class Student
    {
        public int Id { get; set; }
        [DisplayName("First Name")]
        public string? FirstName { get; set; }
        [DisplayName("Last Name")]
        public string? LastName { get; set; }
        [DisplayName("Date of Birth")]
        public DateTime DateOfBirth { get; set; }

    }
}

ASP.NETSchool/Controllers/FileUploadController.cs
using ASP.NETSchool.Models;
using ASP.NETSchool.Services;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Xml;

namespace ASP.NETSchool.Controllers
{
    public class FileUploadController : Controller
    {
        private StudentService _studentService;

        public FileUploadController(StudentService studentService)
        {
            _studentService = studentService;
        }

        public async Task<IActionResult> UploadAsync(IFormFile file) // musi byt stejny nazev jako ve formu v create formu name="file"
        {
            if(file.Length > 0)
            {
                string filePath = Path.GetFullPath(file.FileName);
                using(var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                    stream.Close();
                    XmlDocument xmlDocument = new XmlDocument();
                    xmlDocument.Load(filePath);
                    XmlElement rootNode = xmlDocument.DocumentElement;
                    foreach(XmlNode node in rootNode.SelectNodes("/Students/Student"))
                    {
                        Student newStudent = new Student()
                        {
                            FirstName = node.ChildNodes[0].InnerText,
                            LastName = node.ChildNodes[1].InnerText,
                            DateOfBirth = DateTime.Parse(node.ChildNodes[2].InnerText, CultureInfo.CreateSpecificCulture("cs-cz"))  // specifikace jazyka kvuli Azure
                        };
                        await _studentService.CreateStudentAsync(newStudent);
                    }
                }
                return RedirectToAction("Index", "Students");
            }
            return View("NotFound");
        }
    }
}

ASP.NETSchool/Controllers/StudentsController.cs
using ASP.NETSchool.Models;
using ASP.NETSchool.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NETSchool.Controllers
{
    [Authorize(Roles = "Teacher, Admin")]
    public class StudentsController : Controller
    {
        public StudentService service;

        public StudentsController(StudentService studentService)
        {
            this.service = studentService;
        }

        public async Task<IActionResult> IndexAsync()   // async za indexem .net core ignoruje
        {
            var allStudents = await service.GetAllAsync();
            return View(allStudents);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(Student student)
        {
            await service.CreateStudentAsync(student);
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Edit(int id)
        {
            var studentToEdit = await service.GetById(id);
            if (studentToEdit == null)
            {
                return View("NotFound");
            }
            return View(studentToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, [Bind("Id, FirstName, LastName, DateOfBirth")] Student student)
        {
            await service.UpdateAsync(student);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var studentToDelete = await service.GetById(id);
            if (studentToDelete == null)
            {
                return View("NotFound");
            }
            await service.DeleteAsync(studentToDelete);
            return RedirectToAction("Index");
        }
    }
}

ASP.NETSchool/Views/Students/Create.cshtml
@model Student
<form asp-controller="FileUpload" asp-action="Upload" enctype="multipart/form-data">
    <div class="m-2">
        <input type="file" name="file" />
        <input type="submit" value="Upload" />
    </div>
</form>
<form asp-action="Create">
    <div class="form-group">
        <label asp-for="@Model.FirstName"></label>
        <input type="text" asp-for="@Model.FirstName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.LastName"></label>
        <input type="text" asp-for="@Model.LastName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.DateOfBirth"></label>
        <input type="date" asp-for="@Model.DateOfBirth" class="form-control" />
    </div>
    <input class="btn btn-success m-2" type="submit" value="Create" />
</form>

ASP.NETSchool/Views/Students/Edit.cshtml
@model Student
<form asp-action="Edit">
    <div class="form-group">
        <label asp-for="@Model.FirstName"></label>
    <input type="text" asp-for="@Model.FirstName" class="form-control" /> 
    </div>
    <div class="form-group">
        <label asp-for="@Model.LastName"></label>
        <input type="text" asp-for="@Model.LastName" class="form-control" /> 
    </div>
    <div class="form-group">
        <label asp-for="@Model.DateOfBirth"></label>
        <input type="date" asp-for="@Model.DateOfBirth" class="form-control" />
    </div>
    <input class="btn btn-success m-2" type="submit" value="Update" />
</form>

ASP.NETSchool/Views/Students/Index.cshtml
@model IEnumerable<Student>

<h3>List of students</h3>
<a class="btn btn-success mb-2" asp-action="Create">Create new</a>
@foreach (var student in Model)
{
    <div class="border border-1 border-dark p-2 rounded mb-2">
        <h5>@student.FirstName @student.LastName</h5>
        <p>Id:@student.Id</p>
        <p>Date of Birth: @student.DateOfBirth.ToShortDateString()</p>
        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@student.Id">Edit</a>
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@student.Id">Delete</a>
    </div>
}